### KONFIGURACJA BAZY DANYCH H2 ###
spring.datasource.url=jdbc:h2:mem:przychodniadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

### KONSOLA H2 ###
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

### KONFIGURACJA JPA / HIBERNATE ###
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

### INICJALIZACJA DANYCH (data.sql) ###
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

### OMIJANIE BŁĘDU OPEN-IN-VIEW ###
spring.jpa.open-in-view=false